apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    run: zipkin-server
spec:
  ports:
  - name: port1
    protocol: TCP
    port: 9411
    nodePort: 30666
  selector:
    run: zipkin-service
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-service
  labels:
    run: zipkin-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: zipkin-service
    spec:
      containers:
      - name: zipkin-service
        image: art.local:8081/docker/notebook-microservices-k8s/zipkin-service:latest
        env:
          - name: zipkin-server
            value: "192.168.99.100"
        ports:
        - containerPort: 9411
          protocol: TCP
      imagePullSecrets:
      - name: regcred-local
#TODO fix k8s